# deploy/docker-compose.yaml
services:
  web:
    image: <registry>/projetalgorithmique2groupe7:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      - ./instances:/app/instances  # bind mount pour les fichiers JSON
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s